name: Blue-green Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Сборка и пуш Docker образа
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Тестирование Docker образа
        run: |
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          echo "Testing image: $IMAGE_TAG"

          docker run -d --name test-container -p 3000:3000 "$IMAGE_TAG"

          echo "Ожидание запуска сервера..."
          ok=0
          for i in {1..20}; do
            if curl -fsS http://localhost:3000 > /dev/null; then
              echo "Health check passed"
              ok=1
              break
            fi
            sleep 2
          done

          if [ "$ok" -ne 1 ]; then
            echo "Health check failed"
            docker logs test-container || true
            docker stop test-container || true
            docker rm test-container || true
            exit 1
          fi

          docker stop test-container
          docker rm test-container

  blue-green-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Деплой на сервер
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            /srv/medicine/switch-slots.sh
     

